Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,13 +45,14 @@ jobs:
       - name: Get npm cache directory path
         id: npmCacheDirPath
         if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
+        shell: pwsh # Explicitly use PowerShell for clarity
         run: |
-            dir=$(npm config get cache)
-            if [ -z "$dir" ]; then
-              echo "Error: npm cache directory path is empty." >&2
-              exit 1
-            fi
-            echo "dir=$dir" >> $GITHUB_OUTPUT
+          $dir = npm config get cache
+          if ([string]::IsNullOrEmpty($dir)) {
+            Write-Error "Error: npm cache directory path is empty."
+            exit 1
+          }
+          echo "dir=$dir" >> $GITHUB_OUTPUT
       - name: Cache npm directory
         if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
         uses: actions/cache@v4
